### ISSUE TITLE
[gql_build] ensure all serializer return types (all types?) are available in generated file, or allow import config

### ISSUE THREAD

**Issue by danielmahon** [gql-dart/gql#143]
@smkhalsa Issue created from our DIscord discussion

A custom serializer's return type that is imported from another file is not shown in `serializers.gql.dart` causing a build error.

Only happens with generated BuiltLists? I have other custom scalars set-up the same way but `addBuilderFactory` functions are not generated for them so this problem doesn't occur...

Also, the `addBuilderFactory` function is generated multiple times...

Note: `build_runner build` is still successful

### Error
```
lib/graphql/schema/serializers.gql.g.dart:182:59: Error: Getter not found: 'MyModel'.
          const FullType(BuiltList, const [const FullType(MyModel)]),
                                                          ^^^^^^^^^^^^^^
lib/graphql/schema/serializers.gql.g.dart:183:33: Error: 'MyModel' isn't a type.
          () => new ListBuilder<MyModel>())
                                ^^^^^^^^^^^^^^
```

### Example

```graphql
# schema.g.graphql
#...
"""JSON encoded custom scalar type"""
scalar MyModelPlural

type Foo {
  id: String!
  items: [MyModelPlural!]
}
#...
```

```yaml
# build.yaml
#...
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: flutter_app|lib/graphql/schema/schema.g.graphql
          type_overrides:
            MyModelsPlural:
              name: MyModel
              import: 'package:flutter_app/models/my_model.dart'
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: flutter_app|lib/graphql/schema/schema.g.graphql
          custom_serializers:
            - import: 'package:flutter_app/graphql/serializers/my_model_serializer.dart'
              name: MyModelSerializer
#...
``` 

```dart
// my_model_serializer.dart

// ignore: implementation_imports
import 'package:gql_code_builder/src/serializers/json_serializer.dart';

// This import exposes "MyModel" which will be required, but missing, from serializers.gql.dart
import 'package:flutter_app/models/my_model.dart';

class MyModelSerializer extends JsonSerializer<MyModel> {
  @override
  MyModel fromJson(Map<String, dynamic> data) {
    return MyModel.fromJson(data);
  }
  @override
  Map<String, dynamic> toJson(MyModel model) {
    return model.toJson();
  }
}
```

```dart
// serializers.gql.dart

//...
// Correctly exposes "MyModelSerializer" but NOT "MyModel", causing built file to have missing type
import 'package:flutter_app/graphql/serializers/my_model_serializer.dart'
    show MyModelSerializer;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OtherSerializer())
  ..add(MyModelSerializer())
//...
```

```dart
// serializers.gql.g.dart

//...
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(MyModel)]),
          () => new ListBuilder<MyModel>()))
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(MyModel)]),
          () => new ListBuilder<MyModel>()))
     ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(MyModel)]),
          () => new ListBuilder<MyModel>()))
//...
```
