### ISSUE TITLE
[gql_websocket_link] Unable to add dependency along with ferry ^0.9.1

### ISSUE THREAD

**Issue by ram231** [gql-dart/gql#172]
Hi, I tried to install both `ferry` and `gql_websocket_link` together and had an error when I install it.

**Steps to reproduce**
1. flutter create ferry_websocket
2. add these dependencies
```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  ferry: ^0.9.1
  gql_http_link: ^0.3.2
  gql_link: ^0.3.1
  gql_websocket_link: ^0.1.5-alpha+1605887736172

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  gql_build: ^0.1.3
  gql_code_builder: ^0.1.3
  ferry_generator: ^0.3.1
```

**Actual Result**
```sh
# Example Flutter project
$ flutter pub get
Because no versions of ferry match >0.9.1 <0.10.0 and ferry 0.9.1 depends on rxdart ^0.25.0-beta3, ferry ^0.9.1 requires rxdart ^0.25.0-beta3.
And because every version of gql_websocket_link depends on rxdart ^0.24.0, ferry ^0.9.1 is incompatible with gql_websocket_link.
So, because ferry_websocket depends on both ferry ^0.9.1 and gql_websocket_link ^0.1.5-alpha+1605887736172, version solving failed.
Running "flutter pub get" in ferry_websocket ...
pub get failed (1; So, because ferry_websocket depends on both ferry ^0.9.1 and gql_websocket_link ^0.1.5-alpha+1605887736172, version solving failed.)
```
**Solution:**
The solution I did was to update rxdart dependency in `gql_websocket_link`. I tried to fork it, change the version, and update the dependency. But I still get an error.
```yaml
# gql_websocket_link's pubspec.yaml
dependencies: 
  meta: ^1.1.8
  gql_exec: ^0.2.5
  gql_link: ^0.3.1
  uuid_enhanced: ^3.0.2
  rxdart: ^0.25.0-beta3 #previously ^0.24.0
  gql: ^0.12.3
  web_socket_channel: ^1.1.0
dev_dependencies: 
  test: ^1.14.3
  mockito: ^4.1.1
  gql_pedantic: ^1.0.2
```
