### ISSUE TITLE
gql_websocket_link cannot get added into pubspec.yaml

### ISSUE THREAD

**Issue by warcayac** [gql-dart/gql#246]
Info:

- OS: Manjaro Linux x86_64 
- Kernel: 5.12.9-1-MANJARO
- Flutter: 2.2.2 • channel stable
- Dart: 2.13.3
- VSCode : 1.57.1

packages in `pubspec.yaml` file:
```
dependencies:
  flutter:
    sdk: flutter
  ferry: ^0.10.3
  get: ^4.1.4
  google_fonts: ^2.1.0
  gql_http_link: ^0.4.0
  gql_websocket_link: ^0.3.1
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  ferry_generator: ^0.4.3
```
When trying to add `gql_websocket_link` package:
```
[tutorial_with_hasura_server] flutter pub get
Running "flutter pub get" in tutorial_with_hasura_server...     
Because no versions of ferry match >0.10.3 <0.11.0 and ferry 0.10.3 depends on rxdart ^0.27.1, ferry ^0.10.3 requires rxdart ^0.27.1.
And because gql_websocket_link >=0.3.0-alpha+1621196644743 depends on rxdart ^0.26.0, ferry ^0.10.3 is incompatible with gql_websocket_link >=0.3.0-alpha+1621196644743.
So, because tutorial_with_hasura_server depends on both ferry ^0.10.3 and gql_websocket_link ^0.3.1, version solving failed.


pub get failed (1; So, because tutorial_with_hasura_server depends on both ferry ^0.10.3 and gql_websocket_link ^0.3.1, version solving failed.)
exit code 1
```
Same result with `gql_websocket_link: ^0.3.2-alpha+1623575727762`
