### ISSUE TITLE
How to use serializer?

### ISSUE THREAD

**Issue by yukitaka13-1110** [gql-dart/gql#256]
I defined my serializer, `AWSDate` <-> `DateTime`.
Generate code and request by using it.
But serializer is not working.

MyQuery
```graphql
query GetXxx($id: String!, $date: AWSDate!) {
    getXxx(id: $id, date: $date) {
        ...Xxx
    }
}
```

MySerializer
```dart
import 'package:built_value/serializer.dart';

class AWSDate implements PrimitiveSerializer<DateTime> {
  @override
  DateTime deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "DateSerializer expected 'String' but got ${serialized.runtimeType}");
    return DateTime.parse(serialized is String ? serialized : "");
  }

  @override
  Object serialize(
    Serializers serializers,
    DateTime date, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final dateTimeStr = DateTime.parse(date.toString()).toLocal();
    final dateStr = dateTimeStr.toString().split(' ')[0];
    return dateStr;
  }

  @override
  Iterable<Type> get types => [DateTime];

  @override
  String get wireName => "AWSDate";
}

```

Request
```dart
final variables = GGetXxxVarsBuilder()
      ..id = id
      ..date = dateTIme; // <- type is `DateTime`
final response = await Amplify.API
        .query<dynamic>(
          request: GraphQLRequest<dynamic>(
            document: gql.printNode(document),
            variables: variables.build().toJson(),
          ),
        )
        .response;
```

```
Variable 'date' has an invalid value. Unable to parse `2021-08-04T15:36:46.428775+09:00` as a valid date.
```

How can I serialize?

```dart
[✓] Flutter (Channel unknown, 2.2.0, on Mac OS X 10.15.4 19E287 darwin-x64, locale ja-JP)
    • Flutter version 2.2.0 at /Users/xxxx/fvm/versions/2.2.0
    • Framework revision b22742018b (3 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

```

**Comment by yukitaka13-1110** [comment]
I found different serializer, `AWSDateTime`, called instead of `AWSDate`.
But my serializer and `build.yaml` is correct.

**Comment by yukitaka13-1110** [comment]
I think these are overridden by the last.

My yaml is here.
```yaml
type_overrides:
            AWSDate:
              name: DateTime
            AWSTime:
              name: DateTime
            AWSDateTime:
              name: DateTime
```

**Comment by agent3bood** [comment]
Hi 

You have to provide the path to the custom serializer

example https://github.com/gql-dart/gql/blob/d3780d564739db313ed2027a5bf3d51abba8ecd1/codegen/gql_build/README.md#configuration

```
type_overrides:
    CustomStringScalar:
      name: String
     CustomField:
       name: CustomField
       import: 'package:mypackage/custom_field.dart'

```

**Comment by yukitaka13-1110** [comment]
@agent3bood Thank you for your reply!
I already added path and name in serializers field.
I noticed same primitive mappings are overridden by the last mappings.

AWSDate
AWSTime
AWSDateTime <- last mapping 

So AWSDate was overridden by AWSDAAteTime.

Is it possible to avoid this?

**Comment by agent3bood** [comment]
I think you have to define individual serializers for each type so you can override.



``` 
@override
  String get wireName => "AWSDate";
```

Please provide more details, error log.

**Comment by yukitaka13-1110** [comment]
@agent3bood 

### awsdate_serializer.dart
```dart
import 'package:built_value/serializer.dart';
import 'package:flutter/material.dart';

class AWSDate implements PrimitiveSerializer<DateTime> {
  @override
  DateTime deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "DateSerializer expected 'String' but got ${serialized.runtimeType}");
    return DateTime.parse(serialized is String ? serialized : "");
  }

  @override
  Object serialize(
    Serializers serializers,
    DateTIme date, {
    FullType specifiedType = FullType.unspecified,
  }) {
    debugPrint('AWSDate: called');
    final dateTimeStr = DateTime.parse(date.toString()).toLocal();
    final dateStr = dateTimeStr.toString().split(' ')[0];
    return dateStr;
  }

  @override
  Iterable<Type> get types => [DateTime];

  @override
  String get wireName => "AWSDate";
}

```

### awstime_serializer.dart
```dart
import 'package:built_value/serializer.dart';
import 'package:flutter/material.dart';

class AWSTime implements PrimitiveSerializer<DateTime> {
  @override
  DateTime deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "DateSerializer expected 'String' but got ${serialized.runtimeType}");
    return DateTime.parse(serialized is String ? serialized : "");
  }

  @override
  Object serialize(
    Serializers serializers,
    DateTime date, {
    FullType specifiedType = FullType.unspecified,
  }) {
    debugPrint('AWSTime: called');
    final dateTimeStr = DateTime.parse(date.toString()).toLocal();
    final timeStr = dateTimeStr.toString().split(' ')[1];
    return timeStr;
  }

  @override
  Iterable<Type> get types => [DateTime];

  @override
  String get wireName => "AWSTime";
}

```

### awsdatetime_serializer.dart
```dart
import 'package:built_value/serializer.dart';
import 'package:flutter/material.dart';

class AWSDateTime implements PrimitiveSerializer<DateTime> {
  @override
  DateTime deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "DateSerializer expected 'String' but got ${serialized.runtimeType}");
    return DateTime.parse(serialized is String ? serialized : "");
  }

  @override
  Object serialize(
    Serializers serializers,
    DateTime date, {
    FullType specifiedType = FullType.unspecified,
  }) {
    debugPrint('AWSDateTime: called');
    // throw Exception('Noooooo !!!');
    final dateTimeStr = DateTime.parse(date.toString()).toLocal();
    final dateTimeList = dateTimeStr.toString().split(' ');
    return '${dateTimeList[0]}T${dateTimeList[1]}+09:00';
  }

  @override
  Iterable<Type> get types => [DateTime];

  @override
  String get wireName => "AWSDateTime";
}

```

### build.yaml
```yaml
targets:
  $default:
    sources:
      - lib/**
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|req_builder:
        enabled: true
        options:
          schema: my_project|lib/graphql/generated/schema.graphql
          type_overrides:
            AWSDate:
              name: String
            AWSTime:
              name: DateTime
            AWSDateTime:
              name: DateTime
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: my_project|lib/graphql/generated/schema.graphql
          custom_serializers:
            - import: 'package:my_project/graphql/serializers/awsdate_serializer.dart'
              name: AWSDate
            - import: 'package:tenalife_mobile_app/graphql/serializers/awstime_serializer.dart'
              name: AWSTime
            - import: 'package:my_project/graphql/serializers/awsdatetime_serializer.dart'
              name: AWSDateTime
          type_overrides:
            AWSDate:
              name: String
            AWSTime:
              name: DateTime
            AWSDateTime:
              name: DateTime
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            AWSDate:
              name: String
            AWSTime:
              name: DateTime
            AWSDateTime:
              name: DateTime
      gql_build|data_builder:
        enabled: true
        options:
          schema: my_project|lib/graphql/generated/schema.graphql
          type_overrides:
            AWSDate:
              name: String
            AWSTime:
              name: DateTime
            AWSDateTime:
              name: DateTime
      gql_build|var_builder:
        enabled: true
        options:
          schema: my_project|lib/graphql/generated/schema.graphql
          type_overrides:
            AWSDate:
              name: String
            AWSTime:
              name: DateTime
            AWSDateTime:
              name: DateTime
```

### serializers.gql.dart
```dart
final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..add(AWSDate())
  ..add(AWSTime())
  ..add(AWSDateTime())
  ..addPlugin(StandardJsonPlugin());
.
.
.
```

If I build variables, `AWSDateTime` serializer is used.
```
flutter: AWSDateTime: called
```

If I comment out and execute, `AWSTime` is used.
### serializers.gql.dart
```dart
final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..add(AWSDate())
  ..add(AWSTime())
  // ..add(AWSDateTime())
  ..addPlugin(StandardJsonPlugin());
.
.
.
```

```
flutter: AWSTime: called
```

If I comment out more and execute, `AWSDate` is used.
```dart
final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..add(AWSDate())
  // ..add(AWSTime())
  // ..add(AWSDateTime())
  ..addPlugin(StandardJsonPlugin());
.
.
.
```

```
flutter: AWSDate: called
```
