### ISSUE TITLE
Future of gql_dio_link

### ISSUE THREAD

**Issue by knaeckeKami** [gql-dart/gql#384]
Since dio is now [officially unmaintained](https://github.com/flutterchina/dio), we'll have to decide what we'll do with gql_dio_link.

There is a hard fork called diox: https://pub.dev/packages/diox

It would be great if dio was handed to the folks working on diox so that there is a smooth transition, but it looks like this will not happen.

Possible routes we can take:

- leave gql_dio_link as is, it should work with diox if users do the "hard fork override" and rewrite dependencies of dio to diox
with
```yaml 
dependency_overrides:
  dio:
    git:
      url: https://github.com/cfug/diox
      path: dio/
      ref: dio
```
If there are breaking changes in the future, this might break though.

- migrate gql_dio_link to diox

- keep gql_dio_link, deprecate it, fork off gql_diox_link

Looking forward to feedback from impacted users.
